### ISSUE TITLE
Purposer block stopped updating usefulness and jewel order

### ISSUE THREAD

**Issue by rahelest** [ImplementsLegend/VaultJewelPurposer#2]
A few weeks ago the purposer stopped sorting the jewels when I adjusted the weights or switched the config pages. Jewel order changes somewhat while the router was pulling jewels out of the block, but as soon as I stopped the router, jewel order (and usefulness) stopped getting updated as well. 

When mining and re-placing the block, all weight values are replaced with NaN.
![2024-01-21_13 33 47](https://github.com/ImplementsLegend/VaultJewelPurposer/assets/3957611/4053f203-5595-4575-b81f-f77876742aff)

Creating a new weight set the first time in this NaN state crashed the Minecraft client with IndexOutOfBoundsException. 
Re-running the client, the purposer seems to be reset to the "freshly created" state, with one default set, but changing the weights still does not re-order the jewels. Re-placing the block gets it back to the NaN state but adding a new set doesn't crash the client anymore.

Attached client crash report. Didn't notice any lines appearing to the debug or latest log while using the purposer.
[crash-2024-01-21_13.21.30-client.txt](https://github.com/ImplementsLegend/VaultJewelPurposer/files/14001064/crash-2024-01-21_13.21.30-client.txt)

**Comment by ImplementsLegend** [comment]
That crash was caused by pressing '>' and then '+'. That's because '>' would try to increment index of selected "weight set" and if it was then more than number of existing set, it would then limit the index. So if there were 0 sets, it would set that index from 0 (default value) to -1 and if you then try to create new one, it would crash.

Sorting was broken because I did not like that it sorted all jewels every tick so I changed that without realising that buttons would stop sorting.

New version is released. It should solve these issues.
